- name: Install GPG on Ubuntu
  apt:
    name: gpg
  when: ansible_distribution == 'Ubuntu'

- name: Remove legacy NodeSource repository
  file:
    path: /etc/apt/sources.list.d/deb_nodesource_com_node_14_x.list
    state: absent
  when: nodejs.version is defined

- name: Add NodeSource package signing key
  apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /usr/share/keyrings/nodesource.gpg
  when: nodejs.version is defined

- name: Add NodeSource repository
  copy:
    content: "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs.version }}.x {{ ansible_distribution_release }} main"
    dest: /etc/apt/sources.list.d/nodesource.list
  when: nodejs.version is defined

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: Configure apt proxy
  when: system.apt.proxy
  loop:
    - /etc/apt/apt.conf.d/proxy.conf
  copy:
    content: |
      Acquire::http::Proxy "{{ system.apt.proxy }}";
    dest: "{{ item }}"

- name: Install apt packages
  apt:
    name: "{{ system.apt.packages.items()|selectattr('1', 'eq', true)|map(attribute='0')|list }}"
