- name: Update hosts file
  vars:
    hosts: "{{ system.hosts.values() | select('string') | reject('eq', '') | list }}"
  loop:
    - /etc/hosts
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    block: "{{ hosts | join('\n') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (system)"
    state: "{{ 'present' if hosts | length > 0 else 'absent' }}"
