- name: Template Netplan config
  loop: "{{ system.netplan|dict2items }}"
  loop_control:
    label: "{{ dest }}"
  vars:
    dest: "/etc/netplan/{{ item.key }}"
  copy:
    content: |
      {{ item.value|to_nice_yaml(indent=2) }}
    dest: "{{ dest }}"
  register: system_template_netplan_config_result

- name: Apply Netplan config
  when: system_template_netplan_config_result.changed
  command: netplan apply
