- name: Install Python 3.8
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
  apt:
    update_cache: yes
    name: python3.8

- name: Create directory for Ansible facts
  loop:
    - /etc/ansible/facts.d
  file:
    path: "{{ item }}"
    state: directory

- name: Template proServer fact
  loop:
    - /usr/local/bin/proserver-facts
  template:
    src: proserver.fact.py
    dest: "{{ item }}"
    mode: a+x
  register: system_template_proserver_fact_result

- name: Link proServer fact
  loop:
    - /etc/ansible/facts.d/proserver.fact
  file:
    src: /usr/local/bin/proserver-facts
    dest: "{{ item }}"
    state: link
  register: system_link_proserver_fact_result

- name: Reload facts
  when: system_template_proserver_fact_result.changed or system_link_proserver_fact_result.changed
  changed_when: system_template_proserver_fact_result.changed or system_link_proserver_fact_result.changed
  setup: {}
